name: Run Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.sum'
      - 'go.mod'
      - '.github/workflows/*.yml'
      - '.mise.toml'
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.sum'
      - 'go.mod'
      - '.github/workflows/*.yml'
      - '.mise.toml'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 1

    - uses: jdx/mise-action@v3
      with:
        experimental: true
        cache: true

    - name: Run checks
      run: mise run check
